/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!*/
#define AUTHOR "Thibaut COLIN <thibault.colin@silabs.com>"
#define GIT_DESCRIPTION "2.0.2"
#define GIT_BRANCH "* detached"
#define WFX_VERS 2
#define WFX_SUBVERS 2
#define WFX_BUILD 2.0.2
#define WFX_LABEL "WFX_2.0.2"
