/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!*/
#define AUTHOR "Thibaut COLIN <thibault.colin@silabs.com>"
#define GIT_DESCRIPTION "1.6"
#define GIT_BRANCH "* master"
#define WFX_VERS 1
#define WFX_SUBVERS 1
#define WFX_BUILD 1.6
#define WFX_LABEL "WFX_1.6"
